sudo: required
dist: trusty
language: php
services:
- docker
php:
- '7.2'
before_script: composer install
after_script:
- docker build -t patrikx3/resume/ .
notifications:
  email:
    recipients:
    - alabard@gmail.com
    on_success: change
    on_failure: change
env:
  global:
    secure: t0WhsntI66MDfOe/kmOYjlXtncleKvebx1e42CGol0YQmKKi/84SbJ11TNxBo0fpJc5NNlZBMx/dZnsRVix8ur+tD9wldkB3kKlSkWXM3RnVhnZGyES8yV8npiXk7GwDQmHx8aH76feHCDPC9vSGDEGkwBQJy41/3FlutM2ghPClaRpAqJ7cgD3j73HayITM7ZP6HLCaA/FYzdD6B1c9i6YzgrklJnkyyXf3Q/sxWzcxcjep7HBZFVIMUFMXyJ6pYfe9cpiDTMsm3IWhfJpE0I6Vh6VTAq0jDiLuBhel9Yifvu7lX6VQJj2qp1W7/fbwhhHWvSAkKBMmHsi78VAEmVWwLydsID0KKSW6ZRVchOgqxdaSviskTPrwOdZfwhhkPfal/x1tSySfeFH8InW1AMbK2M5v2stSEbEe67NfAOcGNawomKImciLmfLxirvpbXROVXS70uT0U0JMPR+HU+G+SeXzW59eDGzVLxXYyeLDRRy8n1pTLqsFdveu9L/YBdFWdSH82qFJKIrNhSbercVSbfuogA1mZaBGLj7yUit1uUj+OhKnrC8UMoJttlmG6q3PAyjvz+wygq7WdZfO3XpTasqBUr3E3C9gdf94DeVpcD8G+Cu6ZFqthAOLNzdVulZfanKp60PfvJMdHZx1V/dNAMga4aT8y1/D0TML7IFo=
